In [1]:
import pickle
from keras.preprocessing.image import ImageDataGenerator

In [2]:
x=pickle.load(open('feature.pkl','rb'))

In [3]:
y=pickle.load(open('lebel.pkl','rb'))

In [4]:
x

array([[[[ 59,  49,  92],
         [ 87,  81, 105],
         [162, 162, 157],
         ...,
         [124, 124, 129],
         [123, 120, 126],
         [108, 103, 108]],

        [[ 59,  50,  98],
         [ 72,  67,  95],
         [153, 153, 153],
         ...,
         [125, 124, 130],
         [115, 112, 118],
         [111, 105, 110]],

        [[ 57,  50, 103],
         [ 60,  56,  91],
         [134, 133, 142],
         ...,
         [126, 123, 129],
         [112, 108, 114],
         [115, 109, 114]],

        ...,

        [[ 88,  79,  76],
         [ 88,  74,  69],
         [ 94,  73,  65],
         ...,
         [110,  74,  63],
         [ 91,  60,  49],
         [ 98,  69,  58]],

        [[ 66,  56,  52],
         [ 73,  58,  52],
         [ 88,  66,  57],
         ...,
         [112,  71,  58],
         [ 97,  59,  46],
         [105,  69,  55]],

        [[ 71,  59,  54],
         [ 73,  57,  50],
         [ 79,  56,  46],
         ...,
         [113,  69,  52],
        

In [5]:
x=x/255 #feature scaling for running model in a faster way

In [6]:
x

array([[[[0.23137255, 0.19215686, 0.36078431],
         [0.34117647, 0.31764706, 0.41176471],
         [0.63529412, 0.63529412, 0.61568627],
         ...,
         [0.48627451, 0.48627451, 0.50588235],
         [0.48235294, 0.47058824, 0.49411765],
         [0.42352941, 0.40392157, 0.42352941]],

        [[0.23137255, 0.19607843, 0.38431373],
         [0.28235294, 0.2627451 , 0.37254902],
         [0.6       , 0.6       , 0.6       ],
         ...,
         [0.49019608, 0.48627451, 0.50980392],
         [0.45098039, 0.43921569, 0.4627451 ],
         [0.43529412, 0.41176471, 0.43137255]],

        [[0.22352941, 0.19607843, 0.40392157],
         [0.23529412, 0.21960784, 0.35686275],
         [0.5254902 , 0.52156863, 0.55686275],
         ...,
         [0.49411765, 0.48235294, 0.50588235],
         [0.43921569, 0.42352941, 0.44705882],
         [0.45098039, 0.42745098, 0.44705882]],

        ...,

        [[0.34509804, 0.30980392, 0.29803922],
         [0.34509804, 0.29019608, 0.27058824]

In [7]:
x.shape

(67, 100, 100, 3)

In [8]:
#data augmentaion

In [9]:
dataGen = ImageDataGenerator(width_shift_range=0.1,
                             height_shift_range=0.1,
                             zoom_range=0.2,
                             shear_range=0.1,
                             rotation_range=20,
                             horizontal_flip= True)

In [10]:
pip install keras-tuner

     ------------------------------------ 135.7/135.7 kB 473.4 kB/s eta 0:00:00
     ------------------------------------ 895.7/895.7 kB 308.0 kB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.10.0 requires libclang>=13.0.0, which is not installed.
tensorflow 2.10.0 requires tensorflow-io-gcs-filesystem>=0.23.1, which is not installed.


In [11]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
print(tf.__version__)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout, Activation, Flatten, Conv2D, MaxPooling2D

2.10.0


In [12]:
x[0]

array([[[0.23137255, 0.19215686, 0.36078431],
        [0.34117647, 0.31764706, 0.41176471],
        [0.63529412, 0.63529412, 0.61568627],
        ...,
        [0.48627451, 0.48627451, 0.50588235],
        [0.48235294, 0.47058824, 0.49411765],
        [0.42352941, 0.40392157, 0.42352941]],

       [[0.23137255, 0.19607843, 0.38431373],
        [0.28235294, 0.2627451 , 0.37254902],
        [0.6       , 0.6       , 0.6       ],
        ...,
        [0.49019608, 0.48627451, 0.50980392],
        [0.45098039, 0.43921569, 0.4627451 ],
        [0.43529412, 0.41176471, 0.43137255]],

       [[0.22352941, 0.19607843, 0.40392157],
        [0.23529412, 0.21960784, 0.35686275],
        [0.5254902 , 0.52156863, 0.55686275],
        ...,
        [0.49411765, 0.48235294, 0.50588235],
        [0.43921569, 0.42352941, 0.44705882],
        [0.45098039, 0.42745098, 0.44705882]],

       ...,

       [[0.34509804, 0.30980392, 0.29803922],
        [0.34509804, 0.29019608, 0.27058824],
        [0.36862745, 0

In [13]:
x[0].shape

(100, 100, 3)

In [14]:
model= Sequential()
model.add(Conv2D(64, (3,3),input_shape=x.shape[1:], activation= 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(128,input_shape=x.shape[1:], activation='relu'))

model.add(Dense(2,activation='softmax'))
          

In [15]:
model.compile(loss="sparse_categorical_crossentropy",
             optimizer ="adam",
             metrics =['accuracy'])


In [16]:
model.fit(x,y, epochs=20,validation_split=0.1)

Epoch 1/20
2/2 [==============================] - 2s 826ms/step - loss: 1.6759 - accuracy: 0.5833 - val_loss: 0.6675 - val_accuracy: 0.5714
Epoch 2/20
2/2 [==============================] - 1s 398ms/step - loss: 0.9069 - accuracy: 0.5000 - val_loss: 0.7703 - val_accuracy: 0.4286
Epoch 3/20
2/2 [==============================] - 1s 357ms/step - loss: 0.7046 - accuracy: 0.4833 - val_loss: 0.7105 - val_accuracy: 0.5714
Epoch 4/20
2/2 [==============================] - 1s 364ms/step - loss: 0.5943 - accuracy: 0.6333 - val_loss: 0.7020 - val_accuracy: 0.5714
Epoch 5/20
2/2 [==============================] - 1s 381ms/step - loss: 0.5453 - accuracy: 0.6500 - val_loss: 0.6988 - val_accuracy: 0.5714
Epoch 6/20
2/2 [==============================] - 1s 396ms/step - loss: 0.5200 - accuracy: 0.6500 - val_loss: 0.6652 - val_accuracy: 0.5714
Epoch 7/20
2/2 [==============================] - 1s 382ms/step - loss: 0.4545 - accuracy: 0.8667 - val_loss: 0.6514 - val_accuracy: 0.5714
Epoch 8/20
2/2 [====

In [17]:
model_name="cat_and_dog_own_data_four.h5"
model.save(model_name)

In [18]:
from tensorflow.keras.models import load_model
load_model(model_name)

In [37]:
import keras.utils as image
import numpy as np

img_pred=image.load_img(r"C:\Users\ADMIN\Desktop\IMAGE CLASSIFICATION USING CNN KERAS\CAT\Cat-vs-Dog-identificaton-using-CNN-main\own_dataset\dog\dog.7306.jpg",target_size=(100,100))

img_pred=image.img_to_array(img_pred)
img_pred=np.expand_dims(img_pred, axis=0)
rslt= model.predict(img_pred)

print(rslt)
if rslt[0][0]>rslt[0][1]:
    prediction="cat"
    
    
else:
    prediction="dog"
print(prediction)


1/1 [==============================] - 0s 219ms/step
[[0. 1.]]
dog


In [38]:
#checking my main model size


In [39]:
import os
def get_file_size(file_path):
    size= os.path.getsize(file_path)
    return size
def convert_bytes(size, unit=None):
    if unit== "KB":
        return print ('File size:' +str(round(size/1024,3)) +'kilobytes')
    elif unit=="MB":
         return print ('File size:' +str(round(size/(1024*1024),3)) +'Megabytes')
    else:
         return print ('File size:' +str(size) +'bytes')
convert_bytes(get_file_size(model_name),"MB")

File size:50.086Megabytes


In [40]:
tf_lite_model="second_tflite.tflite"

In [41]:
tf_lite_converter=tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model=tf_lite_converter.convert()

INFO:tensorflow:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpxwy105fs\assets


INFO:tensorflow:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpxwy105fs\assets


In [42]:
#save the model in memory



In [43]:
tflite_model_name= tf_lite_model
open(tflite_model_name, "wb").write(tflite_model)

17494124

In [44]:
convert_bytes(get_file_size(tf_lite_model),"MB")

File size:16.684Megabytes


In [45]:
#evaluate my tflite mode;

In [46]:
interpreter =tf.lite.Interpreter(model_path=tf_lite_model)
input_details=interpreter.get_input_details()
output_details=interpreter.get_output_details()
print("input shape:",input_details[0]['shape'])
print("input type:",input_details[0]['dtype'])
print("output shape:",output_details[0]['shape'])
print("output shape:",output_details[0]['dtype'])

input shape: [  1 100 100   3]
input type: <class 'numpy.float32'>
output shape: [1 2]
output shape: <class 'numpy.float32'>


In [47]:
#making quantized model

In [48]:
tf_lite_model_quantized="second_quantized_tflite.tflite"

In [49]:
tf_lite_converter=tf.lite.TFLiteConverter.from_keras_model(model)

tf_lite_converter.optimizations=[tf.lite.Optimize.DEFAULT]
tf_lite_converter.target_spec.supported_types=[tf.float16]
tflite_model=tf_lite_converter.convert()

INFO:tensorflow:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpaojiuu_q\assets


INFO:tensorflow:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpaojiuu_q\assets


In [50]:
print (tf.__version__)

2.10.0


In [51]:
tflite_model_name= tf_lite_model_quantized
open(tflite_model_name, "wb").write(tflite_model)

8749916

In [52]:
convert_bytes(get_file_size(tf_lite_model_quantized),"MB")

File size:8.345Megabytes
